### PR TITLE
Remove spring, pretty up the template

### PR DESCRIPTION
**Pull request by d4be4st**
Task: [#496](https://app.productive.io/1-infinum/tasks/2150453)

Remove spring from template
Pretty up the template

### CODE REVIEW

**Review by cilim — APPROVED** [review]

**Review by nikajukic — APPROVED** [review]

**Review by uncoverd — CHANGES_REQUESTED** [review]
Did we do any benchmarking on the removal of spring? I know that on M1s and NLBL for example the difference isn't that big, but I remember it being substantial on other projects (maybe Loop) and on my older machine 🤔 

I wouldn't just remove spring based on DHH's will, he's got the latest iMac Pro and a large chunk of the backend team is still on intel based macs. I propose we do a real life test of console boot times and rspec runs on a few representative projects before we go forward with this and consider it the standard

**Comment by cilim** [comment]
> Did we do any benchmarking on the removal of spring? I know that on M1s and NLBL for example the difference isn't that big, but I remember it being substantial on other projects (maybe Loop) and on my older machine 🤔
> 
> I wouldn't just remove spring based on DHH's will, he's got the latest iMac Pro and a large chunk of the backend team is still on intel based macs. I propose we do a real life test of console boot times and rspec runs on a few representative projects before we go forward with this and consider it the standard

Just bear in mind that a lot of people don't use spring, even if it's listed in the Gemfile and bundled on their machines 😄 
And even if they have slower machines than the M1

**Comment by d4be4st** [comment]
> Did we do any benchmarking on the removal of spring? I know that on M1s and NLBL for example the difference isn't that big, but I remember it being substantial on other projects (maybe Loop) and on my older machine 🤔

No, but its kinda broken for `rails` commands anyway.
so `rake db:migrate` uses spring
but `rails db:migrate` does not

https://github.com/rails/spring#rails-console-rails-generate-rails-runner

anyway, if the project team wants spring (like if at one point in time rspec starting become just to long) they can add spring at a later point in the project.

**Comment by d4be4st** [comment]
> Just bear in mind that a lot of people don't use spring, even if it's listed in the Gemfile and bundled on their machines 😄
And even if they have slower machines than the M1

By a lot people you mean you, right @cilim ? :D

**Comment by cilim** [comment]
> > Just bear in mind that a lot of people don't use spring, even if it's listed in the Gemfile and bundled on their machines 😄
> > And even if they have slower machines than the M1
> 
> By a lot people you mean you, right @cilim ? :D

I'm the only one that **admits** I'm not using it, but there are more of us 😁

**Pull request merged**
