### PR TITLE
Feature/launch_rails_app_in_deploy_rb

### PR DESCRIPTION
**Pull request by vlakre**
#### Aim
Update deploy.rb script and force the load of the rails environment to catch missing secrets or anything similar before deploying.

#### Solution
Run random ruby script with rails runner to trigger the rails env load.

### CODE REVIEW

**Review by uncoverd — APPROVED** [review]
What's the time penalty?

**Comment by vlakre** [comment]
@uncoverd about 10sec, according to the Atlas deployment logs.

**Review by vr4b4c — APPROVED** [review]
I understand this solves practical challenge, but you should be aware that this isn't in sync with how application is started in the online env. Here you are starting the app using the `bundle exec` while in the online env it'll be managed using the web application server (probably Passenger). In other words, you could miss certain types of  startup errors (eg. stdlib package version mismatches).

**Comment by vlakre** [comment]
@vr4b4c good point. Is there a way for us to run the app in a way that is in sync with the online env? It would be great to catch package version mismatches and similar issues.

**Comment by vr4b4c** [comment]
I think the problem you are trying to solve should be handled on the infrastructure layer with good observability setup, in this particular case monitoring health-check endpoint + alerting rules to notify the failure

**Comment by vlakre** [comment]
after consulting with @vr4b4c, I see that adding this to the default template is unnecessary as the new projects are moving away from mina. Closing this PR.

**Pull request closed without merging**
